name: Call Deno CI

permissions:
  contents: read
  pull-requests: write

on: pull_request

jobs:
  call-deno-ci:
    uses: pHo9UBenaA/gh-action-templates/.github/workflows/deno-ci.yml@2f463d6d238d218fe2b74b5102b0205d607e4191
